twig:
    default_path: '%kernel.project_dir%/templates'
# config/packages/twig.yaml
    form_themes:
        - 'form/fields.html.twig'
    globals:
        profiles: '%profiles%'
        images: '%images%'
when@test:
    twig:
        strict_variables: true
